package watch

import (
	"flag"
	"math"
	"math/rand/v2"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/sahil87/tu/internal/render/ansi"
)

// seededRain builds a state under a fixed PCG seed (test determinism; the TS
// Math.random sequence is not reproducible anyway — plan assumption 1).
func seededRain(cols, rows, startCol int, seed uint64) *RainState {
	return NewRainState(cols, rows, startCol, rand.New(rand.NewPCG(seed, seed^0x9e37)), ansi.Colors{Enabled: true})
}

// update regenerates the golden files: go test ./internal/watch/ -update
var update = flag.Bool("update", false, "regenerate golden files")

// The TS rain.test.ts cases: 1× at ≤ 20 rows, 3× cap at 60+.
func TestActiveDropCount(t *testing.T) {
	cases := []struct {
		cols, rows, want int
	}{
		{100, 20, 30},  // 1× at the reference height
		{100, 10, 30},  // clamped to 1× below it
		{100, 60, 90},  // 3× cap
		{100, 200, 90}, // capped past 60
		{10, 20, 3},
		{11, 20, 3},   // Math.round(3.3)
		{100, 40, 60}, // 2× scale
	}
	for _, c := range cases {
		if got := ActiveDropCount(c.cols, c.rows); got != c.want {
			t.Errorf("ActiveDropCount(%d, %d) = %d, want %d", c.cols, c.rows, got, c.want)
		}
	}
}

// Init scatters drops (rows in [−length, rows)) with one drop per column
// under the shipped constants, round-robin over the shuffled columns.
func TestRainInit(t *testing.T) {
	r := seededRain(20, 15, 0, 42)
	if len(r.drops) != 6 { // ActiveDropCount(20, 15) = round(20 × 0.3 × 1)
		t.Fatalf("drops = %d, want 6", len(r.drops))
	}
	seen := map[int]bool{}
	for _, d := range r.drops {
		if seen[d.col] {
			t.Errorf("column %d hosts two drops", d.col)
		}
		seen[d.col] = true
		if d.col < 0 || d.col >= 20 {
			t.Errorf("col %d out of range", d.col)
		}
		if d.row < -float64(d.length) || d.row > 15 {
			t.Errorf("row %v outside the scatter range", d.row)
		}
		if d.delay != 0 {
			t.Errorf("scattered drop delay = %d, want 0", d.delay)
		}
		if d.speed < rainMinSpeed || d.speed > rainMaxSpeed {
			t.Errorf("speed %v outside 0.3–1.0", d.speed)
		}
		if d.length < rainMinLength || d.length > rainMaxLength {
			t.Errorf("length %d outside 3–8", d.length)
		}
	}
}

// A respawn: after every tick, no started drop is fully off-screen (the TS
// respawn condition floor(row) − length > rows fires within the same tick).
func TestRainRespawn(t *testing.T) {
	r := seededRain(5, 4, 0, 7)
	for i := 0; i < 200; i++ {
		r.Tick()
		for _, d := range r.drops {
			if d.delay == 0 && math.Floor(d.row)-float64(d.length) > float64(r.rows) {
				t.Fatalf("drop at %v was not respawned (rows %d, length %d)", d.row, r.rows, d.length)
			}
		}
	}
}

// Resize with identical geometry keeps the drops; different geometry
// re-initialises.
func TestRainResize(t *testing.T) {
	r := seededRain(20, 15, 0, 42)
	before := r.drops[0]
	beforeChars := strings.Clone(string(r.drops[0].chars))
	r.Resize(20, 15, 0)
	if len(r.drops) != 6 || r.drops[0].row != before.row || string(r.drops[0].chars) != beforeChars {
		t.Errorf("identical resize re-initialised the drops")
	}
	r.Resize(30, 15, 0)
	if len(r.drops) != ActiveDropCount(30, 15) {
		t.Errorf("resize did not re-initialise: drops = %d", len(r.drops))
	}
	if len(r.prev) != 0 {
		t.Errorf("resize kept prev positions")
	}
}

// The seeded golden: one render, one tick, one render (with the vacated-cell
// clears), under color. Byte references are generated by the seeded RNG and
// hand-verified against the TS render rules (cell order: drops in order,
// head to tail; colors bright-green/green/dim-green; clears after all cells).
func TestRainGolden(t *testing.T) {
	r := seededRain(10, 8, 0, 2026)
	frame1 := r.Render(17)
	r.Tick()
	frame2 := r.Render(17)
	got := frame1 + "===\n" + frame2
	path := filepath.Join("testdata", "rain_seeded.golden")
	if *update {
		if err := os.MkdirAll("testdata", 0o755); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(path, []byte(got), 0o644); err != nil {
			t.Fatal(err)
		}
	}
	raw, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read golden (run with -update to create): %v", err)
	}
	if got != string(raw) {
		t.Errorf("rain frames differ from %s (-update to regenerate)\ngot:\n%q\nwant:\n%q", path, got, string(raw))
	}
	if frame1 == "" || frame2 == "" {
		t.Errorf("frames must be non-empty: %q / %q", frame1, frame2)
	}
	// Every occupied cell of frame 1 that frame 2 vacated is cleared with a
	// cursor-positioned space in frame 2.
	if !strings.Contains(frame2, "H ") {
		t.Logf("no vacated cells in this seed's second frame (possible for slow drops)")
	}
}

// Every previously occupied cell not occupied in the next frame gets a clear.
// Constructed directly so a vacated cell is guaranteed.
func TestRainClearPass(t *testing.T) {
	r := seededRain(10, 8, 0, 1)
	// Plant a deterministic drop: col 3, head at row 6, length 4.
	r.drops = []rainDrop{{col: 3, row: 6, speed: 1, length: 4, chars: []rune("abcd")}}
	frame1 := r.Render(17)
	// Frame 1 occupies rows 3,4,5,6 of col 3 → screen rows 20,21,22,23, col 4.
	for _, want := range []string{"\x1b[23;4H", "\x1b[22;4H", "\x1b[21;4H", "\x1b[20;4H"} {
		if !strings.Contains(frame1, want) {
			t.Errorf("frame 1 lacks %q: %q", want, frame1)
		}
	}
	// Colors: head bright-green, body green while i < length−2, tail dim-green.
	if !strings.Contains(frame1, "\x1b[23;4H\x1b[92ma\x1b[0m") {
		t.Errorf("head cell wrong: %q", frame1)
	}
	if !strings.Contains(frame1, "\x1b[22;4H\x1b[32mb\x1b[0m") {
		t.Errorf("body cell wrong: %q", frame1)
	}
	if !strings.Contains(frame1, "\x1b[20;4H\x1b[2;32md\x1b[0m") {
		t.Errorf("tail cell wrong: %q", frame1)
	}

	r.Tick() // speed 1 → head at 7; the tail leaves row 3
	frame2 := r.Render(17)
	if !strings.Contains(frame2, "\x1b[20;4H ") {
		t.Errorf("frame 2 lacks the vacated-cell clear: %q", frame2)
	}
	if strings.Contains(frame2, "\x1b[20;4H\x1b") {
		t.Errorf("vacated cell redrawn: %q", frame2)
	}
}

// Disabled zone renders nothing.
func TestRainDisabledRender(t *testing.T) {
	r := seededRain(0, 0, 0, 1)
	if got := r.Render(1); got != "" {
		t.Errorf("Render on rows<=0 = %q, want empty", got)
	}
}

// The right-margin column offset: startCol shifts every emitted column.
func TestRainStartColOffset(t *testing.T) {
	r := seededRain(11, 11, 89, 1)
	r.drops = []rainDrop{{col: 0, row: 2, speed: 0, length: 3, chars: []rune("xyz")}}
	frame := r.Render(1)
	// col 0 with startCol 89 → 1-based column 90.
	if !strings.Contains(frame, "\x1b[3;90H") {
		t.Errorf("frame lacks the offset cell: %q", frame)
	}
}
