id: bom7
name: 260717-bom7-rain-density-scale-height
created: 2026-07-17T19:59:22Z
created_by: Sahil Ahuja
change_type: fix
issues: []
progress:
    intake: done
    apply: done
    review: done
    hydrate: done
    ship: done
    review-pr: done
plan:
    generated: true
    task_count: 4
    acceptance_count: 11
    acceptance_completed: 11
confidence:
    certain: 2
    confident: 3
    tentative: 0
    unresolved: 0
    score: 4.8
    fuzzy: true
    dimensions:
        signal: 68.0
        reversibility: 93.0
        competence: 83.0
        disambiguation: 73.0
stage_metrics:
    intake: {started_at: "2026-07-17T19:59:22Z", driver: fab-new, iterations: 1, completed_at: "2026-07-17T20:01:11Z"}
    apply: {started_at: "2026-07-17T20:01:11Z", driver: fab-fff, iterations: 1, completed_at: "2026-07-17T20:07:59Z"}
    review: {started_at: "2026-07-17T20:07:59Z", driver: fab-fff, iterations: 1, completed_at: "2026-07-17T20:21:02Z"}
    hydrate: {started_at: "2026-07-17T20:21:02Z", driver: fab-fff, iterations: 1, completed_at: "2026-07-17T20:22:39Z"}
    ship: {started_at: "2026-07-17T20:22:39Z", driver: fab-fff, iterations: 1, completed_at: "2026-07-17T20:25:00Z"}
    review-pr: {started_at: "2026-07-17T20:25:00Z", driver: git-pr, iterations: 1, completed_at: "2026-07-17T20:30:03Z"}
prs:
    - https://github.com/sahil87/tu/pull/48
true_impact:
    added: 369
    deleted: 5
    net: 364
    excluding:
        added: 105
        deleted: 5
        net: 100
    tests:
        added: 83
        deleted: 1
        net: 82
    computed_at: "2026-07-17T20:25:00Z"
    computed_at_stage: ship
# true_impact: lazily created on first stage-finish that computes it (no placeholder here).
last_updated: 2026-07-17T20:30:03Z
